name: Workflow trigger via repository_dispatch 
on: [ push, workflow_dispatch ] 
jobs:
  shell:
    name: Shell Commands
    runs-on: [ self-hosted, mylabel ]
    steps:
    - uses: actions/checkout@v2 
    - name: Shell test 
      run: |  
        ls -al 
        du -s

 
 
 
  
